### ISSUE TITLE
Unable to upload files - 500 error

### ISSUE THREAD

**Issue by annatech** [it-objects/terraform-aws-terra3#34]
I modified the original terraform to deploy to us-east-1 rather than eu-central-1.  Unfortunately, any attempt to upload files to my Mastodon instance results in at 500 error.

**Comment by w13k** [comment]
Hey @annatech, a quick fix to the problem is to allow public access to the S3 solution bucket using ACL. Since this is a security relevant action and ACL's are deprecated, please be sure about what you're doing. I haven't found a way yet to implement a good solution in Terraform, but this is, how you can get rid of the 500 right away. If I have the time, I'll probably continue working on it. So, any input on this is welcome!

**Comment by annatech** [comment]
Thanks! I will test the change to see if it resolves the 500 error during resource uploads and let you know.

**Comment by annatech** [comment]
I can confirm that changing the media bucket to public access and switching to Bucket Ownership to "Bucket owner preferred" resolved the issue with media uploads saving to S3. It's not an ideal solution, of course,  but it does identify that the S3 permissions / ACL need some refinement. 

Thanks!
